xmrig_ir
splunk/security_content pull request #1381
Opened 2021-05-07 11:48 UTC by tccontre

PR for CPU Miner Found in ATTACK_RANGE - HoneyPOT:

## New XMRIG analytics stories and detections:

stories/xmrig.yml

1.  deleting_of_net_users.yml
2.  disable_windows_app_hotkeys.yml
3.  disabling_net_user_account.yml
4.  download_files_using_telegram.yml
5.  enumerate_users_local_group_using_telegram.yml
6.  excessive_attempt_to_disable_services.yml
7.  excessive_service_stop_attempt.yml
8.  excessive_usage_of_cacls_app.yml
9.  excessive_usage_of_net_app.yml
10.  excessive_usage_of_taskkill.yml
11.  executables_or_script_creation_in_suspicious_path.yml
12.  hide_user_account_from_sign_in_screen.yml
13.  icacls_deny_command.yml
14.  icacls_grant_command.yml
15.  modify_acl_permission_to_files_or_folder.yml
16.  process_kill_base_on_file_path.yml
17.  schtasks_run_task_on_demand_.yml
18.  suspicious_driver_loaded_path.yml
19.  suspicious_process_file_path.yml
20.  xmrig_driver_loaded.yml

## minor description mod:

1. schedule_task_with_rundll32_command_trigger.yml

2021-05-07 13:54 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Excessive Deleting Of Users :white_check_mark:
- diskUsage: 503808
- runDuration: 1.69s
- scanCount: 326

2021-05-07 15:00 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disable Windows App Hotkeys :white_check_mark:
- diskUsage: 389120
- runDuration: 2.019s
- scanCount: 1861

2021-05-07 15:23 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Disabling Net User Account :white_check_mark:
- diskUsage: 286720
- runDuration: 1.743s
- scanCount: 72

2021-05-07 15:29 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Download Files Using Telegram :white_check_mark:
- diskUsage: 294912
- runDuration: 1.122s
- scanCount: 44

2021-05-11 07:19 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Enumerate Users Local Group Using Telegram :white_check_mark:
- diskUsage: 159744
- runDuration: 0.68s
- scanCount: 1

2021-05-11 07:37 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Excessive Attempt To Disable Services :white_check_mark:
- diskUsage: 405504
- runDuration: 129.474s
- scanCount: 271458

2021-05-11 07:46 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Excessive Service Stop Attempt :white_check_mark:
- diskUsage: 413696
- runDuration: 127.265s
- scanCount: 271458

2021-05-11 08:14 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Excessive Usage Of Cacls App :white_check_mark:
- diskUsage: 417792
- runDuration: 133.112s
- scanCount: 271458

2021-05-11 08:20 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Excessive Usage Of Net App :white_check_mark:
- diskUsage: 413696
- runDuration: 129.423s
- scanCount: 271458

2021-05-11 08:43 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Executables Or Script Creation In Suspicious Path :white_check_mark:
- diskUsage: 544768
- runDuration: 3.454s
- scanCount: 2907

2021-05-11 08:44 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Excessive Usage Of Taskkill :white_check_mark:
- diskUsage: 409600
- runDuration: 134.358s
- scanCount: 271458

2021-05-11 09:04 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Hide User Account From Sign-In Screen :white_check_mark:
- diskUsage: 385024
- runDuration: 2.5540000000000003s
- scanCount: 1861

2021-05-11 09:06 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Icacls Deny Command :white_check_mark:
- diskUsage: 503808
- runDuration: 1.481s
- scanCount: 84

2021-05-11 09:28 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

ICACLS Grant Command :white_check_mark:
- diskUsage: 503808
- runDuration: 36.865s
- scanCount: 72969

2021-05-11 09:31 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Modify ACL permission To Files Or Folder :white_check_mark:
- diskUsage: 286720
- runDuration: 1.984s
- scanCount: 49

2021-05-11 10:00 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Schtasks Run Task On Demand :white_check_mark:
- diskUsage: 495616
- runDuration: 44.943s
- scanCount: 97640

2021-05-11 10:01 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Process Kill Base On File Path :white_check_mark:
- diskUsage: 409600
- runDuration: 133.501s
- scanCount: 271458

2021-05-11 10:23 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious Driver Loaded Path :white_check_mark:
- diskUsage: 139264
- runDuration: 0.711s
- scanCount: 40

2021-05-11 10:25 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

XMRIG Driver Loaded :white_check_mark:
- diskUsage: 135168
- runDuration: 1.094s
- scanCount: 59

2021-05-11 10:25 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Suspicious Process File Path :white_check_mark:
- diskUsage: 569344
- runDuration: 2.7880000000000003s
- scanCount: 2830

2021-05-11 14:13 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Ransomware Notes bulk creation :white_check_mark:
- diskUsage: 196608
- runDuration: 1.587s
- scanCount: 524

2021-05-18 08:08 UTC, P4T12ICK commented on detections/endpoint/executables_or_script_creation_in_suspicious_path.yml
> +search: "|tstats `security_content_summariesonly` values(Filesystem.file_path) as\
I think we have too many backslashes in here?

2021-05-18 08:11 UTC, P4T12ICK requested changes

2021-05-18 08:11 UTC, P4T12ICK commented on detections/endpoint/executables_or_script_creation_in_suspicious_path.yml
> +search: "|tstats `security_content_summariesonly` values(Filesystem.file_path) as\
here are many backslashes?

2021-05-18 08:49 UTC, tccontre reviewed
already re copy the original detection I have. thanks for noticing this one

2021-05-18 10:09 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Executables Or Script Creation In Suspicious Path :white_check_mark:
- diskUsage: 540672
- runDuration: 3.8360000000000003s
- scanCount: 2898

2021-05-18 10:52 UTC, P4T12ICK approved these changes, later dismissed

2021-05-19 16:36 UTC, MHaggis submitted a review, later dismissed
Everything looks good. I'd maybe add a bit more data to the analytic story to provide some more context. Otherwise, good to go! :shipit:

2021-05-20 08:57 UTC, tccontre commented
> Everything looks good. I'd maybe add a bit more data to the analytic story to provide some more context. Otherwise, good to go! :shipit:

2021-05-20 14:06 UTC, MHaggis approved these changes

2021-05-20 23:00 UTC, patel-bhavin approved these changes

2021-05-20 23:00 UTC, merged