Printing All your Nightmares
splunk/security_content pull request #1471
Opened 2021-07-01 18:02 UTC by MHaggis

## New Analytics

- Print Spooler Adding A Printer Driver
- Print Spooler Failed to Load a Plug-in
- Spoolsv Spawning Rundll32
- Spoolsv Suspicious Loaded Modules
- Spoolsv Suspicious Process Access
- Spoolsv Writing a DLL
- Spoolsv Writing a DLL - Sysmon

## New Analytic Story

- PrintNightmare CVE-2021-1675

2021-07-01 18:56 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Print Spooler Adding A Printer Driver :white_check_mark:
- diskUsage: 241664
- runDuration: 0.852s
- scanCount: 3

2021-07-01 19:18 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Print Spooler Failed to Load a Plug-in :x:
- diskUsage: 126976
- runDuration: 0.683s
- scanCount: 0

2021-07-01 19:22 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Spoolsv Suspicious Loaded Modules :white_check_mark:
- diskUsage: 139264
- runDuration: 0.754s
- scanCount: 44

2021-07-01 19:22 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Spoolsv Spawning Rundll32 :white_check_mark:
- diskUsage: 425984
- runDuration: 13.423s
- scanCount: 22939

2021-07-01 19:50 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Spoolsv Suspicious Process Access :white_check_mark:
- diskUsage: 139264
- runDuration: 0.788s
- scanCount: 45

2021-07-01 19:51 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Spoolsv Writing a DLL :white_check_mark:
- diskUsage: 749568
- runDuration: 14.065s
- scanCount: 22939

2021-07-01 20:01 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Spoolsv Writing a DLL - Sysmon :white_check_mark:
- diskUsage: 327680
- runDuration: 1.0110000000000001s
- scanCount: 45

2021-07-01 20:17 UTC, d1vious requested changes
some minor changes requested.

2021-07-01 20:17 UTC, josehelps commented on detections/endpoint/print_spooler_adding_a_printer_driver.yml
> +author: Splunk Threat Research Team
hey are we skipping putting the actual author down? :smile:

2021-07-01 20:17 UTC, josehelps commented on detections/endpoint/print_spooler_adding_a_printer_driver.yml
> +  dataset: []
I think we got these now right?

2021-07-01 20:17 UTC, josehelps commented on detections/endpoint/print_spooler_adding_a_printer_driver.yml
> +  - Source: Endpoint
These should be:
```
- Source:Endpoint
- Stage:Persistence
- Stage:Privilege Escalation
- Stage:Defense Evasion
```

2021-07-01 20:17 UTC, josehelps commented on detections/endpoint/print_spooler_failed_to_load_a_plug_in.yml
> +  dataset: []
same comment as above :-)

2021-07-01 20:17 UTC, josehelps commented on detections/endpoint/print_spooler_failed_to_load_a_plug_in.yml
> +  - Stage: Persistence, Privilege Escalation, Defense Evasion
these should be single line values for each, they are meant to be strings

2021-07-01 20:17 UTC, josehelps commented on detections/endpoint/print_spooler_failed_to_load_a_plug_in.yml
> +  - name: EventCode
I would remove this since we really should not track risk or a threat given an event code.

2021-07-01 20:17 UTC, josehelps commented on detections/endpoint/spoolsv_spawning_rundll32.yml
> +  dataset: []
missing

2021-07-01 20:17 UTC, josehelps commented on detections/endpoint/spoolsv_spawning_rundll32.yml
> +  - Processes.parent_process_id
since we are calling drop `drop_dm_object_name(Processes)` above, I believe this the correct fields here are just simply dest, user, parent_process, etc..

2021-07-01 20:17 UTC, josehelps commented on detections/endpoint/spoolsv_spawning_rundll32.yml
> +  context:
see message above, make single line strings

2021-07-01 20:17 UTC, josehelps commented on detections/endpoint/spoolsv_spawning_rundll32.yml
> +    type: Endpoint
I think this should be `Hostname`

2021-07-01 20:17 UTC, josehelps commented on detections/endpoint/spoolsv_spawning_rundll32.yml
> +  - name: parent_process
I would use parent_process_id here instead since it is what we would take action on.

2021-07-01 20:17 UTC, josehelps commented on detections/endpoint/spoolsv_spawning_rundll32.yml
> +    type: Process Name
the type then would change to `Process`

2021-07-01 20:17 UTC, josehelps commented on detections/endpoint/spoolsv_spawning_rundll32.yml
> +  - name: process_name
should be `process_id`

2021-07-01 20:17 UTC, josehelps commented on detections/endpoint/spoolsv_spawning_rundll32.yml
> +    type: Process Name
change type `Process`

2021-07-01 20:17 UTC, d1vious commented on detections/endpoint/spoolsv_suspicious_loaded_modules.yml
> +  | stats dc(ImageLoaded) as countImgloaded values(ImageLoaded) as ImgLoaded count min(_time) as firstTime max(_time) as lastTime by Image Computer EventCode
should we grab the process id out of this, with a PID something downstream to use like phantom.

2021-07-01 20:17 UTC, d1vious commented on detections/endpoint/spoolsv_suspicious_loaded_modules.yml
> +  - name: Image
I would remove this and replace it for a process_id

2021-07-01 20:17 UTC, d1vious commented on detections/endpoint/spoolsv_suspicious_loaded_modules.yml
> +    type: Location
Location is actually geolocation, this should be `File` type.

2021-07-01 20:17 UTC, d1vious commented on detections/endpoint/spoolsv_suspicious_loaded_modules.yml
> +    type: Location
Location is actually geolocation, this should be `File` type.

2021-07-01 20:17 UTC, d1vious commented on detections/endpoint/spoolsv_suspicious_process_access.yml
> +  - Stage: Privilege Escalation, Defense Evasion
see my other comments on how to write these, single line string.

2021-07-01 20:17 UTC, d1vious commented on detections/endpoint/spoolsv_suspicious_process_access.yml
> +  - name: SourceImage
maybe make this a process ID?

2021-07-01 20:17 UTC, d1vious commented on detections/endpoint/spoolsv_writing_a_dll.yml
> +  - Filesystem.dest
drop `Filesystem` and `Process` from these objects.

2021-07-01 20:17 UTC, d1vious commented on detections/endpoint/spoolsv_writing_a_dll.yml
> +    type: Location
should be `File` type.

2021-07-01 20:17 UTC, d1vious commented on detections/endpoint/spoolsv_writing_a_dll___sysmon.yml
> +  - Stage: Privilege Escalation, Defense Evasion
split these into their own line, and single string eg `Stage:Privilege Escalation`

2021-07-01 20:17 UTC, d1vious commented on detections/endpoint/spoolsv_writing_a_dll___sysmon.yml
> +    type: Location
Type should be `File`

2021-07-01 20:17 UTC, d1vious commented on detections/endpoint/spoolsv_writing_a_dll___sysmon.yml
> +    role:
I would change this to process_id .. but you should then bring that into the results in the stats count.

2021-07-01 20:30 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Print Spooler Adding A Printer Driver :white_check_mark:
- diskUsage: 241664
- runDuration: 1.173s
- scanCount: 3

2021-07-01 20:36 UTC, patel-bhavin commented on detections/endpoint/print_spooler_adding_a_printer_driver.yml
> +author: Splunk Threat Research Team
updated :L Mauricio Velazco, Michael Haag, Splunk

2021-07-01 20:37 UTC, patel-bhavin commented on detections/endpoint/print_spooler_failed_to_load_a_plug_in.yml
> +  - name: EventCode
done~

2021-07-01 20:39 UTC, patel-bhavin commented on detections/endpoint/spoolsv_spawning_rundll32.yml
> +  - Processes.parent_process_id
these are required fields for the detections to run, we run the detection sigs  before that DM is dropped

2021-07-01 20:40 UTC, patel-bhavin commented on detections/endpoint/spoolsv_spawning_rundll32.yml
> +    type: Endpoint
it should be `dest` as the search name is based on DM , will update accordingly

2021-07-01 21:12 UTC, patel-bhavin commented on detections/endpoint/spoolsv_suspicious_loaded_modules.yml
> +  - name: Image
updated the SPL and the name

2021-07-01 21:20 UTC, patel-bhavin commented on detections/endpoint/spoolsv_writing_a_dll.yml
> +  - Filesystem.dest
these are required fields to run the search, not the output

2021-07-01 21:25 UTC, patel-bhavin commented on detections/endpoint/spoolsv_suspicious_process_access.yml
> +  - name: ProcessID
@d1vious : this specific search/event  doesnt have a `process_id`  field as how we normally do, the native log itself has a field `ProcessID` which i added to the search

2021-07-02 15:03 UTC, d1vious approved these changes

2021-07-02 15:06 UTC, merged