minor updates given the feedback on issue 1767
splunk/security_content pull request #1769
Opened 2021-10-29 14:55 UTC by d1vious

tiny little changes, also this detection should be moved to prod since it has data ..

2021-10-29 18:25 UTC, trogdorsey requested changes
For completeness, I'd put spaces before the dashes as well.

2021-11-03 22:10 UTC, P4T12ICK commented
This PR was created by Automated Detection Testing Service :robot:

Tested detections:

Windows AdFind Exe :white_check_mark:
- diskUsage: 528384
- runDuration: 17.871s
- scanCount: 29045

2021-11-03 22:12 UTC, patel-bhavin approved these changes

2021-11-03 22:55 UTC, trogdorsey approved these changes

2021-11-03 22:57 UTC, merged