Anomalous usage of account credentials
splunk/security_content pull request #1875
Opened 2021-12-08 18:24 UTC by ljstella

Tied to BA Insider Threat work. This detection is under experimental for two reasons:

- It relies on estdc() instead of dc() which is an undocumented feature of SPS
- the lack of values() non-numeric aggregation feature at this time, which destroys any context related to this anomaly.

2021-12-09 21:00 UTC, d1vious commented
@ljstella given the two limitations above can we:
1. move it to stable by giving a test and a data set
2. add to the body a field called "drilldown" with a string of a search that would allow the user to find the context before the stats command? 
3

2021-12-09 21:00 UTC, d1vious requested changes
lets add a test file for this and move it to stable

2022-01-24 18:42 UTC, ljstella reviewed
Dataset & test generated and added, moved back to experimental per conversation w/ @d1vious

2022-01-24 20:57 UTC, d1vious approved these changes

2022-01-27 22:52 UTC, patel-bhavin approved these changes

2022-01-27 22:55 UTC, merged