Cover xml winevents t1021.002 executable file written in administrative smb share
splunk/security_content pull request #2169
Opened 2022-04-14 01:06 UTC by mr-splunk

# PR Template for new Detections

For Authors:
- [ ] Make sure that CI/CD [detection-testing and build-and-validate](https://github.com/splunk/security_content/actions) jobs passed ✔️. 

For Reviewers:
- [ ] Verify CI/CD jobs have passed without errors.
- [ ] Validate SPL logic.
- [ ] Validate tags, description, and how to implement.
- [ ] Validate name matches `<platform>_<mitre att&ck technique>_<short description>`
- [ ] Verify references match analytic.
- [ ] Is there an Atomic Test?

2022-04-14 21:31 UTC, d1vious requested changes
This looks good to me, only minor thing

2022-04-14 21:31 UTC, d1vious commented on detections/endpoint/executable_file_written_in_administrative_smb_share.yml
> +    EventCode=5145
looks like there is an extra newline char here.

2022-04-15 15:30 UTC, mr-splunk commented on detections/endpoint/executable_file_written_in_administrative_smb_share.yml
> +    EventCode=5145
Ah, added that extra line for ease of readability. Force of habit :)

2022-04-15 15:47 UTC, mr-splunk commented on detections/endpoint/executable_file_written_in_administrative_smb_share.yml
> +    EventCode=5145
Went ahead and removed the newline char, so it looks like this when copy/pasted:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/91983279/163591753-963b4971-9d45-4ff5-810b-6e2c530e9583.png">

2022-05-02 17:29 UTC, d1vious commented
Hey @mr-splunk we chatted about this in a call earlier last week, in short we should not handle the logic for TAs in the detection although super important you raised this. For now I will close this PR and not merge since we will push this fixes down the pike.

2022-05-02 17:29 UTC, closed without merging