crowdstrike_oauth_api_dynamic_analysis_playbooks
splunk/security_content pull request #2585
Opened 2023-03-23 11:21 UTC by tccontre

##### Please check all that apply:
- [x] New playbook
- [ ] Bugfix
- [ ] Feature add
- [ ] Code style update (formatting, renaming)
- [ ] Documentation
- [ ] Other (please describe): 

# Release Notes
Replace the following list with release notes that describe the high level components of the PR:
- [x]  playbooks/CrowdStrike_OAuth_API_Dynamic_Analysis.json
- [x]  new file:   playbooks/CrowdStrike_OAuth_API_Dynamic_Analysis.png
- [x]  new file:   playbooks/CrowdStrike_OAuth_API_Dynamic_Analysis.py
- [x]  new file:   playbooks/CrowdStrike_OAuth_API_Dynamic_Analysis.yml

# Playbook quality checklist
Please check if your PR fulfills the following requirements.

### Requirements for Settings

- [x] Playbook name is A-Z in Title case with underscores between words. (e.g. MS_Graph_Search_and_Purge)
- [ ] Category in Title case with spaces between words (e.g. Identifier Reputation Analysis)
- [x] Description is free of grammatical errors and describe what the playbook does.
- [x] Notes list any setup required on the third-party API as well as intended areas for customization.
- [ ] Label is set to '\*'
    
### Requirements for all playbooks

- [ ] Playbook block count not greater than 15 (not including Start and End blocks).
- [ ] No more than 3 branching paths.
- [x] If referencing a custom list, Notes document what the expected values are in that custom list.

### Requirements for all playbook blocks

- [x] All blocks have a custom name no more than 4 words, all lowercase, and separated by space (e.g. close workbook task)
- [x] All blocks that support a Notes Tooltip have it filled out. Must be grammatically correct and describes the intended purpose of that block.
- [x] Where custom code is used, block notes indicate presence of custom code (e.g. "This block uses custom code")
- [x] No block is disabled by custom code
- [x] Custom code is documented with notes

### Requirements for specific blocks

##### Action

- [x] Use apps available on Splunkbase
- [x] Use asset names that are the app name, all lowercase separated by underscores (e.g. Azure AD Graph becomes azure_ad_graph)

##### Utility 

- [x] Block is using community version

##### Playbook

- [x] Block is using local version

### Requirements for specific playbooks

##### Input playbooks
- [x] Start blocks use ocsf variable names and a minimum of one data type per variable name (e.g. device (type: host name))
- [x] Has at least one category tag (e.g. reputation)
- [x] Playbook has a tag for each vendor app used

# Other considerations (PR type specific)
- [x] If new playbook, there is a screenshot ending in .png with the same name as the playbook .json
- [x] Playbook major minor version matches repo (e.g. 5.5 != 6.0)
- [x] PR contains both .py and .json

---
Thanks for contributing!

2023-03-23 11:25 UTC, tccontre commented on playbooks/CrowdStrike_OAuth_API_Dynamic_Analysis.py
> +@phantom.playbook_block()
feel free to add the actual mac sandbox for mac file detonation part.

2023-03-24 12:55 UTC, P4T12ICK requested changes
- Add Category Dynamic Analysis
- Vault ID Observables vault_id: _vault_id need to be renamed to value: _vault_id.
- Do we need a new category tag instead of reputation? Maybe dynamic_analysis? Reputation is used for another set of playbooks.
- In Playbook Settings, tag for vendor app need to be added.

2023-03-24 12:57 UTC, tccontre commented
> * Add Category Dynamic Analysis
> * Vault ID Observables vault_id: _vault_id need to be renamed to name: _vault_id.
> * Do we need a new category tag instead of reputation? Maybe dynamic_analysis? Reputation is used for another set of playbooks.
> * In Playbook Settings, tag for vendor app need to be added.

2023-03-24 14:48 UTC, tccontre commented
> * Add Category Dynamic Analysis
> * Vault ID Observables vault_id: _vault_id need to be renamed to value: _vault_id.
> * Rename tag reputation to sandbox and update it in observables.
> * In Playbook Settings, tag for vendor app need to be added.
> * End Block need to be configured to return observables and report

all done. :)

2023-03-28 08:13 UTC, P4T12ICK requested changes
- [ ] Remove / Comment debug statements in code blocks

Testing was good. vault_id can only work with a list of same file types (e.g. windows). But I think there is no other way to handle it.

2023-03-28 08:15 UTC, P4T12ICK approved these changes

2023-03-29 17:22 UTC, merged