Identifier Activity Analysis Dispatch
splunk/security_content pull request #2610
Opened 2023-04-10 22:13 UTC by ljstella

##### Please check all that apply:
- [x] New playbook
- [ ] Bugfix
- [ ] Feature add
- [ ] Code style update (formatting, renaming)
- [ ] Documentation
- [ ] Other (please describe): 

# Release Notes
Replace the following list with release notes that describe the high level components of the PR:
- [x]  new file:   playbooks/Identifier_Activity_Analysis_Dispatch.json
- [x]  new file:   playbooks/Identifier_Activity_Analysis_Dispatch.png
- [x]  new file:   playbooks/Identifier_Activity_Analysis_Dispatch.py
- [x]  new file:   playbooks/Identifier_Activity_Analysis_Dispatch.yml

# Playbook quality checklist
Please check if your PR fulfills the following requirements.

### Requirements for Settings

- [x] Playbook name is A-Z in Title case with underscores between words. (e.g. MS_Graph_Search_and_Purge)
- [x] Category in Title case with spaces between words (e.g. Identifier Reputation Analysis)
- [x] Description is free of grammatical errors and describe what the playbook does.
- [x] Notes list any setup required on the third-party API as well as intended areas for customization.
- [x] Label is set to '\*'
    
### Requirements for all playbooks

- [X] Playbook block count not greater than 15 (not including Start and End blocks).
- [X] No more than 3 branching paths.
- [ ] If referencing a custom list, Notes document what the expected values are in that custom list.

### Requirements for all playbook blocks

- [x] All blocks have a custom name no more than 4 words, all lowercase, and separated by space (e.g. close workbook task)
- [x] All blocks that support a Notes Tooltip have it filled out. Must be grammatically correct and describes the intended purpose of that block.
- [ ] Where custom code is used, block notes indicate presence of custom code (e.g. "This block uses custom code")
- [x] No block is disabled by custom code
- [x] Custom code is documented with notes

### Requirements for specific blocks

##### Action

- [ ] Use apps available on Splunkbase
- [ ] Use asset names that are the app name, all lowercase separated by underscores (e.g. Azure AD Graph becomes azure_ad_graph)

##### Utility 

- [x] Block is using community version

##### Playbook

- [X] Block is using local version

### Requirements for specific playbooks

# Other considerations (PR type specific)
- [x] If new playbook, there is a screenshot ending in .png with the same name as the playbook .json
- [x] Playbook major minor version matches repo (e.g. 5.5 != 6.0)
- [x] PR contains both .py and .json

---
Thanks for contributing!

2023-04-14 14:38 UTC, P4T12ICK requested changes
- End block is not connected and not configured
- Decision and Filter blocks need custom name, description, note
- Second add comment need name, desciption, note

2023-04-29 22:08 UTC, kelby-shelton commented
1. Missing D3fend tag D3-IAA
2. Format block should be an aggregate of all child playbook reports.
Current:
<img width="474" alt="Screenshot 2023-04-29 at 5 05 14 PM" src="https://user-images.githubusercontent.com/69353980/235325980-27f4543b-4b22-4922-85ca-df5786c1242b.png">
Desired:
<img width="439" alt="Screenshot 2023-04-29 at 5 07 33 PM" src="https://user-images.githubusercontent.com/69353980/235326014-84c1e8d6-7f21-4e81-ba14-a4c6dfa581dc.png">
<img width="425" alt="Screenshot 2023-04-29 at 5 07 39 PM" src="https://user-images.githubusercontent.com/69353980/235326015-4cf2c34a-0201-4eb4-9652-435e04a585de.png">

2023-05-04 20:27 UTC, ljstella commented
RE: `merge_reports` action for the markdown notes:

Because the dispatch_playbooks portion returns fully formatted tables from each of the inputs, including headers, merging them should be just a matter of looping over each one and including white space at the bottom of each loop to allow for separation. I don't think we need to duplicate the work done in the input playbook here?

2023-05-19 14:23 UTC, P4T12ICK approved these changes

2023-05-19 14:24 UTC, merged