AzureAD Updated Detections
splunk/security_content pull request #2729
Opened 2023-06-16 18:46 UTC by mvelazc0

### Details

_What does this PR have in it? Screenshots are worth 1000 words 😄_

### Checklist

- [ ] Validate name matches `<platform>_<mitre att&ck technique>_<short description>` nomenclature
- [ ] [CI/CD](https://github.com/splunk/security_content/actions) jobs passed ✔️ 
- [ ] Validated SPL logic.
- [ ] Validated tags, description, and how to implement.
- [ ] Verified references match analytic.

2023-08-17 18:44 UTC, patel-bhavin requested changes

2023-08-17 18:44 UTC, patel-bhavin commented on detections/cloud/azure_active_directory_high_risk_sign_in.yml
> +  rename properties.* as * |  stats values(userPrincipalName) by _time, ipAddress,
Write the search as `| stats values(userPrincipalName) as userPrincipalName`. This way we have userPrincipalName in the final table that gets created.

2023-08-17 18:44 UTC, patel-bhavin commented on detections/cloud/azure_active_directory_high_risk_sign_in.yml
> +  message: A high risk event was identified by Identify Protection for user $properties.userPrincipalName$
remove `properties. `. Should be only `userPrincipalName`. I believe this applies to a bunch of changes in this PR!

2023-08-17 18:47 UTC, mvelazc0 commented on detections/cloud/azure_active_directory_high_risk_sign_in.yml
> +  message: A high risk event was identified by Identify Protection for user $properties.userPrincipalName$
solved, thanks!

2023-08-17 18:48 UTC, mvelazc0 commented on detections/cloud/azure_active_directory_high_risk_sign_in.yml
> +  rename properties.* as * |  stats values(userPrincipalName) by _time, ipAddress,
solved, thanks

2023-08-18 20:27 UTC, patel-bhavin approved these changes

2023-08-18 20:27 UTC, merged