Haaglumination
splunk/security_content pull request #3203
Opened 2024-11-13 16:48 UTC by MHaggis

New Analytic Story
- Lumma Stealer

New Analytics
- Windows RunMRU Command Execution

2024-11-13 17:07 UTC, mvelazc0 commented
love it

2024-11-20 19:38 UTC, patel-bhavin requested changes

2024-11-20 19:38 UTC, patel-bhavin commented on detections/endpoint/windows_bitlockertogo_with_network_activity.yml
> +drilldown_searches:
@MHaggis : you can remove drilldowns for the two Hunting searches

2024-11-20 19:38 UTC, patel-bhavin commented on detections/endpoint/windows_bitlockertogo_process_execution.yml
> +- name: View the detection results for - "$dest$"
you can remove drilldowns for the two Hunting searches

2024-11-20 19:38 UTC, patel-bhavin commented on detections/endpoint/windows_bitlockertogo_process_execution.yml
> +    type: User Name
can we change this type to User? we recently cleaned up all our yamls to make it consitent.

2024-11-20 20:15 UTC, patel-bhavin submitted a review, later dismissed

2024-11-20 20:17 UTC, patel-bhavin approved these changes

2024-11-20 20:17 UTC, merged